package com.lungguard.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/*
 * @Entity
 * Tells JPA/Hibernate that this class should become a database table.
 */
@Entity

/*
 * Table name in MySQL.
 */
@Table(name = "risk_assessments")

/*
 * Lombok annotations generate:
 * Getters
 * Setters
 * Constructors
 * Builder Pattern
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RiskAssessment {

    /*
     * Primary Key
     */
    @Id

    /*
     * Auto increment ID
     */
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /*
     * User Information
     */
    private Integer age;

    private String gender;

    private Double weight;

    /*
     * Smoking Information
     */
    private Integer cigarettesPerDay;

    private Integer smokingYears;

    /*
     * Alcohol Information
     */
    private String alcoholFrequency;

    /*
     * Symptoms
     * true = Yes
     * false = No
     */
    private boolean hasCough;

    private boolean hasChestPain;

    private boolean hasBreathlessness;

    /*
     * Calculated by RiskService
     */
    private Integer lungRiskScore;

    private Integer liverRiskScore;

    /*
     * LOW
     * MEDIUM
     * HIGH
     */
    private String riskCategory;

    /*
     * Recommendation generated by system
     */
    @Column(length = 1000)
    private String recommendation;

    /*
     * Assessment creation time
     */
    private LocalDateTime createdAt;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private User user;
}