package com.lungguard.service;

import com.lungguard.dto.XrayResponse;
import com.lungguard.model.User;
import com.lungguard.model.XrayReport;
import com.lungguard.repository.UserRepository;
import com.lungguard.repository.XrayReportRepository;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.time.LocalDateTime;
import java.util.List;

@Service
public class XrayService {

    private final XrayReportRepository xrayReportRepository;
    private final UserRepository userRepository;
    private final AiClientService aiClientService;

    public XrayService(XrayReportRepository xrayReportRepository,
                       UserRepository userRepository,
                       AiClientService aiClientService) {
        this.xrayReportRepository = xrayReportRepository;
        this.userRepository = userRepository;
        this.aiClientService = aiClientService;
    }

    public XrayResponse uploadXray(MultipartFile file) {
        String email = SecurityContextHolder.getContext().getAuthentication().getName();
        User user = userRepository.findByEmail(email)
                .orElseThrow(() -> new RuntimeException("User not found"));

        XrayResponse aiResponse = aiClientService.analyzeXray(file);

        XrayReport report = new XrayReport();

        report.setFileName(file.getOriginalFilename());
        report.setFileType(file.getContentType());

        report.setPrediction(aiResponse.getPrediction());
        report.setConfidence(aiResponse.getConfidence());
        report.setMessage(aiResponse.getMessage());
        report.setClinicalSummary(aiResponse.getClinicalSummary());
        report.setRecommendation(aiResponse.getRecommendation());
        report.setDisclaimer("This is an AI-assisted screening result and does not constitute a medical diagnosis. The analysis is generated by an automated deep learning model and should be reviewed by a qualified healthcare professional. Always consult a licensed physician for clinical decisions.");
        report.setHeatmapBase64(aiResponse.getHeatmapBase64());

        report.setUploadedAt(LocalDateTime.now());
        report.setScanDate(LocalDateTime.now());
        report.setPatientName(user.getFullName());
        report.setUser(user); // Associate the X-ray report with the authenticated user

        xrayReportRepository.save(report);

        return XrayResponse.builder()
                .fileName(report.getFileName())
                .prediction(report.getPrediction())
                .confidence(report.getConfidence())
                .message(report.getMessage())
                .clinicalSummary(report.getClinicalSummary())
                .recommendation(report.getRecommendation())
                .heatmapBase64(report.getHeatmapBase64())
                .build();
    }

    public List<XrayReport> getXrayHistory() {
        String email = SecurityContextHolder.getContext().getAuthentication().getName();
        User user = userRepository.findByEmail(email)
                .orElseThrow(() -> new RuntimeException("User not found"));

        return xrayReportRepository.findByUserOrderByUploadedAtDesc(user);
    }

    public XrayReport getReportById(Long id) {
        String email = SecurityContextHolder.getContext().getAuthentication().getName();
        User user = userRepository.findByEmail(email)
                .orElseThrow(() -> new RuntimeException("User not found"));

        XrayReport report = xrayReportRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Report not found"));

        if (!report.getUser().getId().equals(user.getId())) {
            throw new RuntimeException("Unauthorized access to report");
        }

        return report;
    }
}